# Generated by Django 3.1.5 on 2021-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField(default=' ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp')),
            ],
        ),
    ]
